<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Promise</h2>
    <p>The Promise object represents the eventual completion (or failure) of an asynchronous operation and its resulting value.</p> <br>
    <p>A Promise is in one of these states:</p>
    <ul>
        <li>pending: initial state, neither fulfilled nor rejected.</li>
        <li>fulfilled: meaning that the operation was completed successfully.</li>
        <li>rejected: meaning that the operation failed.</li>
    </ul>
<script>
    const promiseOne = new Promise(function(resolve, reject){
    // an async task
    setTimeout(function(){
        console.log('Async task is compelete');
        resolve()
    }, 1000);
})

promiseOne.then(function(){
    console.log("Promise consumed");
})

new Promise(function(resolve, reject){
    setTimeout(function(){
        console.log("Async task 2");
        resolve()
    }, 1000);

}).then(function(){
    console.log("Async 2 resolved");
})

const promiseThree = new Promise(function(resolve, reject){
    setTimeout(function(){
        resolve({username: "Shalini", email: "abc@gmail.com"})
    }, 1000);
})

promiseThree.then(function(user){
    console.log(user);
})

const promiseFour = new Promise(function(resolve, reject){
    setTimeout(function(){
        let error = true
        if (!error) {
            resolve({username: "Shalini", password: "xyz"});
        } 
        else {
            reject('ERROR: Something went wrong');
        }
    }, 1000);
})

 promiseFour.then((user) => {
    console.log(user);
    return user.username;
}).then((username) => {
    console.log(username);
}).catch(function(error){
    console.log(error);
}).finally(() => console.log("The promise is either resolved or rejected"));



const promiseFive = new Promise(function(resolve, reject){
    setTimeout(function(){
        let error = true
        if (!error) {
            resolve({username: "javascript", password: "123"});
        } else {
            reject('ERROR: JS went wrong');
        }
    }, 1000);
});

async function consumePromiseFive(){
    try {
        const response = await promiseFive;
        console.log(response);
    } catch (error) {
        console.log(error);
    }
}

consumePromiseFive()

//fetch

async function getAllUsers(){
    try {
       const response = await fetch('https://jsonplaceholder.typicode.com/users');

       const data = await response.json();
       console.log(data);
   } catch (error) {
       console.log("E: ", error);
   }
}

getAllUsers();


fetch('https://api.github.com/users/techshalinii')
.then((response) => {
    return response.json();
})
.then((data) => {
    console.log(data);
})
.catch((error) => console.log(error));

</script>
</body>
</html>